-- MySQL Script generated by MySQL Workbench
-- 12/01/15 16:12:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `movies` ;

-- -----------------------------------------------------
-- Table `movies`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`people` ;

CREATE TABLE IF NOT EXISTS `movies`.`people` (
  `idPeople` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `FirstName` VARCHAR(45) NOT NULL COMMENT '',
  `LastName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPeople`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idPeople` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`movies` ;

CREATE TABLE IF NOT EXISTS `movies`.`movies` (
  `idMovies` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Title` VARCHAR(100) NOT NULL COMMENT '',
  `Year` YEAR NULL COMMENT '',
  `Length` INT NULL COMMENT '',
  `Description` TEXT(1200) NULL COMMENT '',
  `Poster` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idMovies`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idMovies` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`countries` ;

CREATE TABLE IF NOT EXISTS `movies`.`countries` (
  `idCountries` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idCountries`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idCountries` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`countries_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`countries_movies` ;

CREATE TABLE IF NOT EXISTS `movies`.`countries_movies` (
  `idCountries_Movies` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fkCountries` INT NOT NULL COMMENT '',
  `fkMovies` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCountries_Movies`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idCountries_Movies` ASC)  COMMENT '',
  INDEX `fk_Country-Film_Country1_idx` (`fkCountries` ASC)  COMMENT '',
  INDEX `fk_Country-Film_Film1_idx` (`fkMovies` ASC)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`fkCountries` ASC, `fkMovies` ASC)  COMMENT '',
  CONSTRAINT `fk_Country-Film_Country1`
    FOREIGN KEY (`fkCountries`)
    REFERENCES `movies`.`countries` (`idCountries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Country-Film_Film1`
    FOREIGN KEY (`fkMovies`)
    REFERENCES `movies`.`movies` (`idMovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`sources` ;

CREATE TABLE IF NOT EXISTS `movies`.`sources` (
  `idSources` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(500) NOT NULL COMMENT '',
  PRIMARY KEY (`idSources`)  COMMENT '',
  UNIQUE INDEX `idSources_UNIQUE` (`idSources` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`paths`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`paths` ;

CREATE TABLE IF NOT EXISTS `movies`.`paths` (
  `idPaths` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fkSources` INT NOT NULL COMMENT '',
  `Name` VARCHAR(500) NOT NULL COMMENT '',
  PRIMARY KEY (`idPaths`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idPaths` ASC)  COMMENT '',
  INDEX `fk_paths_sources1_idx` (`fkSources` ASC)  COMMENT '',
  CONSTRAINT `fk_paths_sources1`
    FOREIGN KEY (`fkSources`)
    REFERENCES `movies`.`sources` (`idSources`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`genres` ;

CREATE TABLE IF NOT EXISTS `movies`.`genres` (
  `idGenres` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idGenres`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idGenres` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`genres_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`genres_movies` ;

CREATE TABLE IF NOT EXISTS `movies`.`genres_movies` (
  `idGenres_Movies` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fkGenres` INT NOT NULL COMMENT '',
  `fkMovies` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idGenres_Movies`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idGenres_Movies` ASC)  COMMENT '',
  INDEX `fk_Genre-Film_Genre1_idx` (`fkGenres` ASC)  COMMENT '',
  INDEX `fk_Genre-Film_Film1_idx` (`fkMovies` ASC)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`fkGenres` ASC, `fkMovies` ASC)  COMMENT '',
  CONSTRAINT `fk_Genre-Film_Genre1`
    FOREIGN KEY (`fkGenres`)
    REFERENCES `movies`.`genres` (`idGenres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Genre-Film_Film1`
    FOREIGN KEY (`fkMovies`)
    REFERENCES `movies`.`movies` (`idMovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`types` ;

CREATE TABLE IF NOT EXISTS `movies`.`types` (
  `idTypes` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTypes`)  COMMENT '',
  UNIQUE INDEX `idtypes_UNIQUE` (`idTypes` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`files` ;

CREATE TABLE IF NOT EXISTS `movies`.`files` (
  `idFiles` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fkTypes` INT NOT NULL COMMENT '',
  `fkPaths` INT NOT NULL COMMENT '',
  `fkMovies` INT NULL COMMENT '',
  `Name` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`idFiles`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idFiles` ASC)  COMMENT '',
  INDEX `fk_File_Film1_idx` (`fkMovies` ASC)  COMMENT '',
  INDEX `fk_files_types1_idx` (`fkTypes` ASC)  COMMENT '',
  INDEX `fk_files_path1_idx` (`fkPaths` ASC)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`fkMovies` ASC, `fkTypes` ASC, `fkPaths` ASC)  COMMENT '',
  CONSTRAINT `fk_File_Film1`
    FOREIGN KEY (`fkMovies`)
    REFERENCES `movies`.`movies` (`idMovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_types1`
    FOREIGN KEY (`fkTypes`)
    REFERENCES `movies`.`types` (`idTypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_path1`
    FOREIGN KEY (`fkPaths`)
    REFERENCES `movies`.`paths` (`idPaths`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`types_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`types_role` ;

CREATE TABLE IF NOT EXISTS `movies`.`types_role` (
  `idTypes_role` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTypes_role`)  COMMENT '',
  UNIQUE INDEX `idTypes_UNIQUE` (`idTypes_role` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`people_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`people_movies` ;

CREATE TABLE IF NOT EXISTS `movies`.`people_movies` (
  `idPeople_Movies` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fkPeople` INT NOT NULL COMMENT '',
  `fkTypes_Role` INT NOT NULL COMMENT '',
  `fkMovies` INT NOT NULL COMMENT '',
  INDEX `fk_people_has_movies_people1_idx` (`fkPeople` ASC)  COMMENT '',
  PRIMARY KEY (`idPeople_Movies`)  COMMENT '',
  UNIQUE INDEX `idMovies_Actors_UNIQUE` (`idPeople_Movies` ASC)  COMMENT '',
  INDEX `fk_persons_movies_Types1_idx` (`fkTypes_Role` ASC)  COMMENT '',
  INDEX `fk_persons_movies_movies1_idx` (`fkMovies` ASC)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`fkPeople` ASC, `fkTypes_Role` ASC, `fkMovies` ASC)  COMMENT '',
  CONSTRAINT `fk_people_has_movies_people1`
    FOREIGN KEY (`fkPeople`)
    REFERENCES `movies`.`people` (`idPeople`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_movies_Types1`
    FOREIGN KEY (`fkTypes_Role`)
    REFERENCES `movies`.`types_role` (`idTypes_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_movies_movies1`
    FOREIGN KEY (`fkMovies`)
    REFERENCES `movies`.`movies` (`idMovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`studios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`studios` ;

CREATE TABLE IF NOT EXISTS `movies`.`studios` (
  `idStudios` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(120) NOT NULL COMMENT '',
  PRIMARY KEY (`idStudios`)  COMMENT '',
  UNIQUE INDEX `idStudios_UNIQUE` (`idStudios` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`studios_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`studios_movies` ;

CREATE TABLE IF NOT EXISTS `movies`.`studios_movies` (
  `idStudios_Movies` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fkStudios` INT NOT NULL COMMENT '',
  `fkMovies` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idStudios_Movies`)  COMMENT '',
  INDEX `fk_movies_has_studios_studios1_idx` (`fkStudios` ASC)  COMMENT '',
  INDEX `fk_movies_has_studios_movies1_idx` (`fkMovies` ASC)  COMMENT '',
  UNIQUE INDEX `idStudios_Movies_UNIQUE` (`idStudios_Movies` ASC)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`fkStudios` ASC, `fkMovies` ASC)  COMMENT '',
  CONSTRAINT `fk_movies_has_studios_movies1`
    FOREIGN KEY (`fkMovies`)
    REFERENCES `movies`.`movies` (`idMovies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_has_studios_studios1`
    FOREIGN KEY (`fkStudios`)
    REFERENCES `movies`.`studios` (`idStudios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
